### ISSUE TITLE
Configurable region

### ISSUE THREAD

**Issue by avoidik** [simonw/llm-bedrock#11]
Hello,

It seems the AWS region is now hardcoded to Oregon (us-west-2). It would be great to have an option to be able to select some other supported region.

https://github.com/simonw/llm-bedrock/blob/main/llm_bedrock.py#L11

Regards

**Comment by simonw** [comment]
Landed in https://github.com/simonw/llm-bedrock/commit/85d9158a6a9002622b051f13f31fe5bad748ee77
