### ISSUE TITLE
ValidationException) when calling the ConverseStream operation: The document file name can only contain...

### ISSUE THREAD

**Issue by simonw** [simonw/llm-bedrock#8]
Ran this:
```bash
llm -u -m nova-pro -a https://comptroller.defense.gov/Portals/45/Documents/defbudget/FY2025/FY2025_Budget_Request.pdf 'convert this document to markdown'
```
Got this:

> `Error: An error occurred (ValidationException) when calling the ConverseStream operation: The document file name can only contain alphanumeric characters, whitespace characters, hyphens, parentheses, and square brackets. The name can't contain more than one consecutive whitespace character. Check that the file name conforms to these restrictions and retry your request.`

Because I used a default filename of `attachment.pdf`.

**Comment by Med5KDB** [comment]
Hey @simonw, 
I'm facing the same issue. I provided `cv.pdf` as filename.
Would you mind to provide me any fix or workaround. I supposed you find out a solution since the issue is close?

**Comment by PaulCdz** [comment]
how do u fixed it ?
